# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecg_viewer_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 734)
        MainWindow.setMinimumSize(QtCore.QSize(800, 734))
        MainWindow.setMaximumSize(QtCore.QSize(800, 734))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-heart-monitor-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graph = PlotWidget(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(10, 10, 781, 421))
        self.graph.setObjectName("graph")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 440, 781, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(50, 115))
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_track = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.show_track.setToolTip("")
        self.show_track.setToolTipDuration(60)
        self.show_track.setWhatsThis("")
        self.show_track.setObjectName("show_track")
        self.horizontalLayout.addWidget(self.show_track)
        self.button_reset = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_reset.setObjectName("button_reset")
        self.horizontalLayout.addWidget(self.button_reset)
        self.button_run = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_run.setObjectName("button_run")
        self.horizontalLayout.addWidget(self.button_run)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_connect = QtWidgets.QPushButton(self.frame)
        self.button_connect.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_connect.setObjectName("button_connect")
        self.gridLayout_2.addWidget(self.button_connect, 4, 1, 1, 1)
        self.button_refresh = QtWidgets.QPushButton(self.frame)
        self.button_refresh.setMaximumSize(QtCore.QSize(16777215, 50))
        self.button_refresh.setObjectName("button_refresh")
        self.gridLayout_2.addWidget(self.button_refresh, 4, 0, 1, 1)
        self.port_combo_box = QtWidgets.QComboBox(self.frame)
        self.port_combo_box.setObjectName("port_combo_box")
        self.gridLayout_2.addWidget(self.port_combo_box, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame_2.setGeometry(QtCore.QRect(10, 610, 261, 90))
        self.gridFrame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.high_limit_box = QtWidgets.QSpinBox(self.gridFrame_2)
        self.high_limit_box.setMinimum(85)
        self.high_limit_box.setMaximum(150)
        self.high_limit_box.setProperty("value", 120)
        self.high_limit_box.setObjectName("high_limit_box")
        self.gridLayout_3.addWidget(self.high_limit_box, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.alarm_mute = QtWidgets.QCheckBox(self.gridFrame_2)
        self.alarm_mute.setObjectName("alarm_mute")
        self.gridLayout_3.addWidget(self.alarm_mute, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.low_limit_box = QtWidgets.QSpinBox(self.gridFrame_2)
        self.low_limit_box.setMinimum(15)
        self.low_limit_box.setMaximum(70)
        self.low_limit_box.setProperty("value", 40)
        self.low_limit_box.setObjectName("low_limit_box")
        self.gridLayout_3.addWidget(self.low_limit_box, 2, 1, 1, 1)
        self.alarm_window = QtWidgets.QFrame(self.centralwidget)
        self.alarm_window.setGeometry(QtCore.QRect(280, 610, 511, 91))
        self.alarm_window.setStyleSheet("QFrame { background-color: red }")
        self.alarm_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alarm_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alarm_window.setObjectName("alarm_window")
        self.alarm_text = QtWidgets.QLabel(self.alarm_window)
        self.alarm_text.setGeometry(QtCore.QRect(10, 10, 491, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.alarm_text.setFont(font)
        self.alarm_text.setScaledContents(True)
        self.alarm_text.setAlignment(QtCore.Qt.AlignCenter)
        self.alarm_text.setObjectName("alarm_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIYECG Viewer"))
        self.label.setText(_translate("MainWindow", "Approximate BPM"))
        self.show_track.setText(_translate("MainWindow", "Show signal tracking"))
        self.button_reset.setText(_translate("MainWindow", "Reset"))
        self.button_run.setText(_translate("MainWindow", "Stop"))
        self.button_connect.setText(_translate("MainWindow", "Connect"))
        self.button_refresh.setText(_translate("MainWindow", "Refresh"))
        self.label_2.setText(_translate("MainWindow", "Device:"))
        self.label_3.setText(_translate("MainWindow", "Alarm Control:"))
        self.label_4.setText(_translate("MainWindow", "High Limit:"))
        self.alarm_mute.setText(_translate("MainWindow", "Mute"))
        self.label_5.setText(_translate("MainWindow", "Low Limit:"))
        self.alarm_text.setText(_translate("MainWindow", "RATE ALARM"))
from pyqtgraph import PlotWidget
